Should avoid an OutOfMemoryError caused by the formatter.
java.lang.OutOfMemoryError: (Heap Size=49187KB, Allocated=47881KB)
at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:567)
at java.lang.StringBuilder.setLength(StringBuilder.java:44)
at com.frostwire.android.gui.activities.MediaPlayerActivity.stringForTime(MediaPlayerActivity.java:644)

This error was exploding when setLength was trying to allocate a huge array.
Calling .setLength(0) is not enough by looking at its code, however calling trimToSize
will reduce the backing array since we've set its count attribute to zero.