Should avoid NPE.
java.lang.RuntimeException: An unexpected exception occurred
at com.squareup.picasso.Request$1.run(Request.java:114)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4444)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
at com.frostwire.android.gui.views.ImageLoader$RawDataResponse.<init>(ImageLoader.java:190)
at com.frostwire.android.gui.views.ImageLoader$ThumbnailLoader.fromRemote(ImageLoader.java:260)
at com.frostwire.android.gui.views.ImageLoader$ThumbnailLoader.load(ImageLoader.java:243)